EssPortal/Controllers/AppraisalController.cs
using EssPortal.Classes;
using EssPortal.Models;
using EssPortal.PerformanceMgmtRef;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EssPortal.Controllers
{
    [Authorize(Roles = "Employee")]
    public class AppraisalController : BaseController
    {
        string _APP_NOT_FOUND = "Matching appraisal for request was not found.";
        // GET: Appraisal
        public ActionResult Index()
        {
            AppraisalIndexViewModel model = new AppraisalIndexViewModel();
            base.Init();
            ViewBag.IsSupervisor = base.UserIsSupervisor();
            var appraisals = base.Service.GetEmployeeAppraisals(User.Identity.EmployeeNo());
            var pendingApproval = base.Service.GetAppraisalPendingApproval(User.Identity.EmployeeNo()).Appraisals;
            model.Appraisals = appraisals.Appraisals;
            model.PendingApprovals = pendingApproval;
            if (!appraisals.Success)
            {
                Information(appraisals.ErrorMessage, true);
            }
            return View(model);
        }

        public List<BehaviourTemplateGroup> GetBehaviourTemplates(string EmployeeNo)
        {
            base.Init();
            bool hasManagerRole = false;
            var employeeData = base.Service.EmployeeData(EmployeeNo);
            if (employeeData.Success && employeeData.Employee != null)
            {
                hasManagerRole = base.Service.HasManagerialRole(employeeData.Employee.Job_ID);
                var response = base.Service.GetBehaviouralTemplate(hasManagerRole);
                if (response.Success)
                {
                    return response.TemplateGroup;
                }
            }
            return new List<BehaviourTemplateGroup>();
        }

        // Add neccesary initializations to model before returning to the view - Most useful for invalid model situations.
        private void ModelInit(AppraisalViewModel model)
        {
            base.Init();
            var definedRatings = base.Service.PerformaceRatings();
            var rating = base.Service.PerformanceRatingSelectList(""); // TODO LOOK INTO PASSED PARAMETER
            model.DefinedRatings = definedRatings;
            model.Rating = rating;
            foreach (var item in model.PerformanceCriteriaPreCurrYear)
            {
                item.AppraiserAssessmentRating = rating;
                item.SelfAssesmentRating = rating;
            }
            foreach (var item in model.CompetencyCriteriaBehaviour.GroupMembers)
            {
                item.AppraiserAssessmentRating = rating;
                item.SelfAssesmentRating = rating;
            }
        }

        // Create a new appraisal
        public ActionResult SubmitAppraisal()
        {
            AppraisalViewModel model = new AppraisalViewModel();
            base.Init();
            var definedRatings = base.Service.PerformaceRatings();
            var rating = base.Service.PerformanceRatingSelectList(""); // TODO LOOK INTO PASSED PARAMETER
            

            model.Rating = rating;
            model.DefinedRatings = definedRatings;

                      

            model.ObjectiveForNextAppraisal.Add(new PerformanceCriteria());
            model.OpenRoomDiscussion.Add(new PerformanceCriteria() { Objective = "Suggestions about improvements in team/department and/or bank should be discussed" });
            model.OpenRoomDiscussion.Add(new PerformanceCriteria() { Objective = "Optional: What is motivating /demotivating in your work environment?" });
            model.IsAppraiser = false;

            var behaviourTemplates = this.GetBehaviourTemplates(User.Identity.EmployeeNo());

            foreach (var template in behaviourTemplates)
            {
                if (template.GroupName == base.Service.AppraisalCompetencyCriteriaBehaviourKey)
                {
                    model.CompetencyCriteriaBehaviour = template;
                }
                else if (template.GroupName == base.Service.AppraisalSelfAssesementIndividualDevKey)
                {
                    model.SelfAssesementIndividualDev = template;
                }
            }

            // Section  to get data needed to autopopulate the model.
            // Employee and supervisor information
            var employeeNo = this.User.Identity.EmployeeNo();
            var employeeRes = base.Service.EmployeeData(employeeNo);
            var hrSetUp = base.Service.GetHrSetUp();

            

            if (employeeRes.Success && employeeRes.Employee != null)
            {
                var employee = employeeRes.Employee;
                model.DateOfJoining = employee.Date_Of_Joining_the_Company.ToString(DATE_FORMAT);
                model.EmployeeBranch = employee.Global_Dimension_2_Code;
                model.EmployeeName = employee.First_Name + " " + employee.Middle_Name + " " + employee.Last_Name;
                model.EmployeeNo = employee.No;
                model.JobTitle = employee.Job_Title;
                model.AppraisalDate = DateTime.Now.ToString(DATE_FORMAT);


                string appPeriod = !String.IsNullOrWhiteSpace(hrSetUp.Previous_Appraisal_Period) ? hrSetUp.Previous_Appraisal_Period : hrSetUp.Appraisal_Period;
                var previousAppraisal = base.Service.EmployeePreviousYearAppraisal(employee.No, appPeriod);

                model.AppraisalPeriod = hrSetUp.Appraisal_Period;                
                model.DateOfLastAppraisal = previousAppraisal != null ? previousAppraisal.Appraisal_Date.ToString(base.DATE_FORMAT) : ""; //base.Service.EmployeeLastAppraisalDate(employee.No, appPeriod);

                // Get the performance criteria for the previous year.
                if (String.IsNullOrWhiteSpace(hrSetUp.Previous_Appraisal_Period) || previousAppraisal == null || previousAppraisal.HR_Appraisal_Career_Dev_Ques.Length <= 0)
                {
                    //  Initialize a blank Performance criteria.
                    model.PerformanceCriteriaPreCurrYear.Add(new PerformanceCriteria() { AppraiserAssessmentRating = rating, SelfAssesmentRating = rating });
                }
                else
                {
                    foreach (var item in previousAppraisal.HR_Appraisal_Career_Dev_Ques)
                    {
                        model.PerformanceCriteriaPreCurrYear.Add(new PerformanceCriteria
                        {
                            Description = item.Description,
                            Objective = item.Planned_Targets_Objectives,
                            AppraiserAssessmentRating = rating,
                            SelfAssesmentRating = rating
                            //LineNo = item.Line_No
                        });
                    }
                }




                var supervisorRes = base.Service.EmployeeData(employee.Supervisor_ID);
                if (supervisorRes.Success && supervisorRes.Employee != null)
                {
                    var supervisor = supervisorRes.Employee;
                    model.AppraiserJobTitle = supervisor.Job_Title;
                    model.AppraiserName = supervisor.First_Name + " " + supervisor.Middle_Name + " " + supervisor.Last_Name;
                }
                else
                {
                    Information(supervisorRes.ErrorMessage, true);
                }
            }
            else
            {
                Information(employeeRes.ErrorMessage, true);
            }
            ViewBag.IsSupervisor = base.UserIsSupervisor();
            return View(model);
        }

        // Submit a new appraisal.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubmitAppraisal(AppraisalViewModel model)
        {
            base.Init();
            ModelInit(model);
            ViewBag.IsSupervisor = base.UserIsSupervisor();

            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var employeeNo = User.Identity.EmployeeNo();
            string newAppraisalNo = base.Service.InsertAppraisal(employeeNo);

            var appraisalResponse = base.Service.GetAppraisal(newAppraisalNo, employeeNo, "");
            if (appraisalResponse.Success && appraisalResponse.Appraisal != null)
            {
                var modifiedAppraisal = this.UpdateAppraisalSection(appraisalResponse.Appraisal, model);

                // Update the newly created record with other appraisal data.
                List<BehaviourTemplateGroup> templates = new List<BehaviourTemplateGroup>();
                templates.Add(model.CompetencyCriteriaBehaviour);
                templates.Add(model.SelfAssesementIndividualDev);

                // If the button "Send to approver was clicked" the status of the Application is updated and a mail sent to the approver.
                if (model.SendForApproval)
                {
                    appraisalResponse.Appraisal.Status = Status.Pending_Approval;
                    appraisalResponse.Appraisal.StatusSpecified = true;
                }
                base.Service.UpdateAppraisalBehaviourTemplates(appraisalResponse.Appraisal, templates, model.IsAppraiser);
                // Send a mail after the Appraisal has been updated.
                if (model.SendForApproval)
                {
                    base.Service.MailAppraiserNotification(appraisalResponse.Appraisal.Appraisal_No);
                    Information("Thank you for your thoughts and preparing for the appraisal meeting. Your self-assessment has been sent to your supervisor/ appraiser.", true);
                }
                    
                return RedirectToAction("Index");
            }
            else
            {
                string error = String.IsNullOrWhiteSpace(appraisalResponse.ErrorMessage) ? _APP_NOT_FOUND : appraisalResponse.ErrorMessage;
                Danger(error, true);

EssPortal/Views/Appraisal/AppraiserReviewAppraisal.cshtml
@model EssPortal.Models.AppraisalViewModel

@{
    ViewBag.Title = "Review Appraisal";
}

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("AppraiserReviewAppraisal", "Appraisal", new { AppraisalNo = Model.AppraisalNo }, FormMethod.Post, new { @id = "SubmitAppraisal" }))
        {

            @Html.EditorFor(m => m)

            <div class="form-group" style="padding-bottom: 10px">
                <input type="submit" value="Send to HR" class="btn btn-default btn-lg" id="send-to-hr" />
                <input type="submit" value="Send to Appraisee" class="btn btn-default btn-lg" id="send-to-appraisee" />
                <input type="submit" value="Save" class="btn btn-default btn-lg" id="approver-save" />
                @Html.ActionLink("Discard Changes", "Index", "Appraisal", new { @class = "btn btn-default btn-lg" })
            </div>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

@Html.Partial("_AppraisalScripts")
}

EssPortal/Views/Appraisal/Index.cshtml
@model EssPortal.Models.AppraisalIndexViewModel
@{
    ViewBag.Title = "Appraisal";
}

<div class="row">
    <div class="col-lg-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                Appraisal Requests
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover ">
                        <thead>
                            <tr>
                                <th>Appraisal No</th>
                                <th>Appraisal Period</th>
                                <th>Status</th>
                                <th>Appraisal Date</th>                               
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.Appraisals.Count <= 0)
                            {
                                <tr>
                                    <td colspan="5">You currently do not have any appraisals.</td>
                                </tr>
                            }
                            @foreach (var item in Model.Appraisals)
                            {
                                <tr>
                                    <td>@item.Appraisal_No</td>
                                    <td>@item.Appraisal_Period</td>
                                    <td>@item.Status</td>
                                    <td>@item.Appraisal_Date.ToString("dd/MM/yyyy")</td>
                                    <td>
                                        @if (item.Appraisal_Period_Closed)
                                        {
                                            <a href="@Url.Action("ViewAppraisal", "Appraisal", new { AppraisalNo = item.Appraisal_No, IsAppraiser=false })">View</a>
                                        }
                                        else
                                        {
                                            if (item.Status == EssPortal.PerformanceMgmtRef.Status.Appraisee_Review || item.Status == EssPortal.PerformanceMgmtRef.Status.Open)
                                            {

                                                <a href="@Url.Action("ReviewAppraisal", "Appraisal", new { AppraisalNo = item.Appraisal_No })">Edit</a>
                                            }
                                            if (item.Status == EssPortal.PerformanceMgmtRef.Status.Approved || item.Status == EssPortal.PerformanceMgmtRef.Status.Pending_Approval)
                                            {
                                                <a href="@Url.Action("ViewAppraisal", "Appraisal", new { AppraisalNo = item.Appraisal_No, IsAppraiser=false })">View</a>
                                            }
                                        }

                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>


        <div class="row">
            <div class="col-lg-12">

            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <a href="@Url.Action("SubmitAppraisal", "Appraisal")" class="btn btn-default">New Appraisal</a>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                Appraisals Pending Review
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover ">
                        <tbody>
                            @foreach (var item in Model.PendingApprovals)
                            {
                                <tr>
                                    <td><a href="@Url.Action("AppraiserReviewAppraisal", "Appraisal", new { AppraisalNo = item.Appraisal_No })">@item.Employee_Name</a>
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>

       
        @*@Html.Partial("_LeaveBalance", employee)

        @if (Model.UserIsSupervisor)
            {
            @Html.Partial("_PendingLeaveApprovePanel", Model.LeavePendingApproval.Leave)
        }*@
    </div>
</div>

EssPortal/Views/Appraisal/PerformanceCriteria.cshtml
@model EssPortal.Models.PerformanceCriteria

@{
    ViewBag.Title = "Performance Criteria";
}

<h2>PerformanceCriteria</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PerformanceCriteria</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Objective, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Objective, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Objective, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelfAssesment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SelfAssesment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SelfAssesment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AppraiserAssessment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AppraiserAssessment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AppraiserAssessment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EssPortal/Views/Appraisal/ReviewAppraisal.cshtml
@model EssPortal.Models.AppraisalViewModel

@{
    ViewBag.Title = "Review Appraisal";
}

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("ReviewAppraisal", "Appraisal", new { AppraisalNo = Model.AppraisalNo }, FormMethod.Post, new { @id = "SubmitAppraisal" }))
        {

            @Html.EditorFor(m => m)

            <div class="form-group" style="padding-bottom: 10px">
                <input type="submit" value="Send to Appraiser" class="btn btn-default btn-lg" id="submit-appraisal" />
                <input type="submit" value="Save" class="btn btn-default btn-lg" id="save-appraisal" />
                @Html.ActionLink("Discard Changes", "Index", "Appraisal", new {@class= "btn btn-default btn-lg" })
            </div>
        }
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    @Html.Partial("_AppraisalScripts")
}

EssPortal/Views/Appraisal/SubmitAppraisal.cshtml
@model EssPortal.Models.AppraisalViewModel

@{
    ViewBag.Title = "Submit Appraisal";
}

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("SubmitAppraisal", "Appraisal", new { }, FormMethod.Post, new { @id= "SubmitAppraisal" }))
        {

            @Html.EditorFor(m => m)

            <div class="form-group" style="padding-bottom: 10px">
                <input type="submit" value="Send to Appraiser" class="btn btn-default btn-lg" id="submit-appraisal" />
                <input type="submit" value="Save" class="btn btn-default btn-lg" id="save-appraisal" />
                @Html.ActionLink("Discard Changes", "Index", "Appraisal", new { @class = "btn btn-default btn-lg" })
            </div>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    
    @{Html.RenderPartial("_AppraisalScripts");}
}

EssPortal/Views/Appraisal/SupervisorApprovedAppraisal.cshtml
@model EssPortal.Models.AppraisalIndexViewModel
@{
    ViewBag.Title = "Employee Appraisals";
}

<div class="row">
    <div class="col-lg-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                Approved Appraisals
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover ">
                        <thead>
                            <tr>
                                <th>Appraisal No</th>
                                <th>Appraisal Period</th>
                                <th>Status</th>
                                <th>Appraisal Date</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.Appraisals.Count <= 0)
                            {
                                <tr>
                                    <td colspan="5">You currently do not have any appraisals.</td>
                                </tr>
                            }
                            @foreach (var item in Model.Appraisals)
                            {
                                <tr>
                                    <td>@item.Appraisal_No</td>
                                    <td>@item.Appraisal_Period</td>
                                    <td>@item.Status</td>
                                    <td>@item.Appraisal_Date.ToString("dd/MM/yyyy")</td>
                                    <td>
                                        @if (item.Status == EssPortal.PerformanceMgmtRef.Status.Pending_Approval && !item.Appraisal_Period_Closed)
                                        {

                                            <a href="@Url.Action("AppraiserReviewAppraisal", "Appraisal", new { AppraisalNo = item.Appraisal_No })">Review</a>
                                        }
                                        @if (item.Status == EssPortal.PerformanceMgmtRef.Status.Approved)
                                        {
                                            <a href="@Url.Action("ViewAppraisal", "Appraisal", new { AppraisalNo = item.Appraisal_No, IsAppraiser=true })">View</a>
                                        }
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
    </div>

    <div class="col-lg-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                Appraisals Pending Review
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover ">
                        <tbody>
                            @foreach (var item in Model.PendingApprovals)
                            {
                                <tr>
                                    <td>
                                        <a href="@Url.Action("AppraiserReviewAppraisal", "Appraisal", new { AppraisalNo = item.Appraisal_No })">@item.Employee_Name</a>
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>


        @*@Html.Partial("_LeaveBalance", employee)

            @if (Model.UserIsSupervisor)
                {
                @Html.Partial("_PendingLeaveApprovePanel", Model.LeavePendingApproval.Leave)
            }*@
    </div>
</div>

EssPortal/Views/Appraisal/_UseGradingPerformanceTemp.cshtml
@model EssPortal.Models.BehaviourTemplateGroup

<div class="panel panel-default">
    <div class="panel-heading">
        @Model.GroupName
        <a data-toggle="collapse" href="#BiodataPanel"><span class="glyphicon glyphicon-menu-down pull-right"></span></a>
    </div>
    <div class="panel-body panel-collapse" id="BiodataPanel">

        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label class="control-label"> Objective </label>
                </div>
            </div>

            <div class="col-md-4">
                <div class="form-group">
                    <label class="control-label"> Description </label>
                </div>
            </div>

            <div class="col-md-2">
                <div class="form-group">
                    <label class="control-label"> Self Assesment </label>
                </div>
            </div>

            <div class="col-md-2">
                <div class="form-group">
                    <label class="control-label"> Appraiser Assesment </label>
                </div>
            </div>
        </div>

        @for (int i = 0; i < Model.GroupMembers.Count; i++)
        {
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.EditorFor(model => model.GroupMembers[i].Objective, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.GroupMembers[i].Objective, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        @Html.EditorFor(model => model.GroupMembers[i].Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.GroupMembers[i].Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group">
                        @Html.DropDownListFor(model => model.GroupMembers[i].SelfAssesment, Model.Rating, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.GroupMembers[i].SelfAssesment, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group">
                        @Html.DropDownListFor(model => model.GroupMembers[i].AppraiserAssessment, Model.Rating, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.GroupMembers[i].AppraiserAssessment, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        }
    </div>
</div>