EssPortal/Models/LeaveViewModels.cs
using ExpressiveAnnotations.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EssPortal.Models
{
    public class LeaveApplicationViewModel : LeaveInformation
    {
        #region ------------ Properties -----------------------

        [MaxLength(20, ErrorMessage = "Maximum of 20 characters allowed.")]
        public string ApplicationNo { get; set; }

        public string ApplicationDate { get; set; }

        [Required]
        [Display(Name = "Employee No.")]
        public string EmployeeNo { get; set; }

        [Display(Name = "Employee Name")]
        public string EmployeeName { get; set; }

        [Display(Name = "Job Title")]
        public string JobTitle { get; set; }

        public string Branch { get; set; }

        public string Department { get; set; }

        [Display(Name = "Supervisor Name(for Approval)")]
        public string SupervisorName { get; set; }

        [Display(Name = "Supervisor E-Mail")]
        public string SupervisorEmail { get; set; }

        [Required]
        [Display(Name = "Leave Type")]
        public string LeaveType { get; set; }

        [Required]
        [Display(Name = "Leave Start Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public string LeaveStartDate { get; set; }

        [Required]
        [Display(Name = "Leave End Date")]
        [DisplayFormat(ApplyFormatInEditMode =true,DataFormatString = "{0:dd/MM/yyyy}")]
        public string LeaveEndDate { get; set; }

        // To be autoopulated.
        [Range(0.0, 365.0, ErrorMessage = "Enter a value less than the allowed leave balance.")]
        [StringLength(4, ErrorMessage = "Maximum of 4 numeric characters.")]
        [Display(Name = "No. of Leave Days Applied for")]
        public string LeaveDaysAppliedFor { get; set; }

        [Required]
        [Range(0.0, 365.0, ErrorMessage = "Enter a value less than the appllied leave days.")]
        [StringLength(4, ErrorMessage = "Maximum of 4 numeric characters.")]
        [Display(Name = "Approved Leave Days")]
        public string LeaveDaysApproved { get; set; }

        [StringLength(4, ErrorMessage = "Maximum of 4 numeric characters.")]
        [Display(Name = "Total Annual Leave Days")]
        public string TotalAnnualLeaveDays { get; set; }

        [Display(Name = "Start Date of Approved Leave")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public string StartDateOfApprovedLeave { get; set; }

        [Display(Name = "End Date of Approved Leave")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public string EndDateOfApprovedLeave { get; set; }

        [StringLength(4, ErrorMessage = "Maximum of 4 numeric characters.")]
        [Display(Name = "Total Annual Leave Days Taken")]
        public string TotalAnnualLeaveTaken { get; set; }

        [StringLength(4, ErrorMessage = "Maximum of 4 numeric characters.")]
        [Display(Name = "Annual Balance(Days)")]
        public string TotalAnnualLeaveBalance { get; set; }

        [Display(Name = "Annual Leave Days Utilized")]
        public string AnnualLeaveDaysUtilized { get; set; }

        [Required(ErrorMessage ="A reliever code is required.")]
        [Display(Name = "Reliever Name")]
        public string RelieverCode { get; set; }

        [Display(Name = "To Include Half Day")]
        public bool ToIncludeHalfDay { get; set; }

        [Display(Name = "Reliever Name")]
        public string RelieverName { get; set; }

        [Display(Name = "Application Status")]
        public string LeaveApplicationStatus { get; set; }

        [Required]
        [Display(Name = "Rejection Reason")]
        public string RejectionReason { get; set; }

        // used to control certain parts of the page to make editable or not. eg. Rejection Reason and Leave days approved.
        public bool IsSupervisor { get; set; }

        // This fields will be hidden and used to inform the nav wether to save the leave application or send it for approaval.
        // Saving means setting the status flag to NEW while sending it for approval will set the status flag to PENDING APPROVAL.
        public bool SubmitLeave { get; set; }

        public bool Approved { get; set; }

        // the date from which an employee can apply for leave.
        public string ValidLeaveDateFrom { get; set; }
        public int leaveMonths { get; set; }

        public IEnumerable<SelectListItem> Employees { set; get; }

        #endregion --------------------------------------------

    }
}

EssPortal/Controllers/LeaveController.cs
using EssPortal.Classes;
using EssPortal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace EssPortal.Controllers
{
    [Authorize(Roles = "Employee")]
    public class LeaveController : BaseController
    {
        // GET: Leave
        public ActionResult Index()
        {
            base.Init();
            ViewBag.IsSupervisor = base.UserIsSupervisor();
            bool UserIsSupervisor = false;
            var leaveBalance = base.Service.EmployeeData(User.Identity.EmployeeNo());
            if (leaveBalance.Employee == null)
            {
                return View("InvalidEmployeeDetail", InvalidEmployeeDetail());
            }
            UserIsSupervisor = base.Service.HasManagerialRole(leaveBalance.Employee.Job_ID);
            var currentAppliedLeave = base.Service.GetLeaveApplications(User.Identity.EmployeeNo(), AnnualLeaveCode);

            // Get a list of leave applications to be attended to by the currently logged in user.
            var leaveRequestsForApprooval = base.Service.PendingLeaveToApprove(User.Identity.UserInformation().Email);

            LeaveIndexViewModel model = new LeaveIndexViewModel { EmployeeDataResponse = leaveBalance, LeaveResponse = currentAppliedLeave, LeavePendingApproval = leaveRequestsForApprooval };//, LeaveHistoryResponse = historicalLeaveRecord };
            model.UserIsSupervisor = UserIsSupervisor;

            return View(model);
        }

        private string ValidLeaveDateFrom(DateTime EmployeeJoinDate, LeaveApplicationViewModel model)
        {
            base.Init();
            var setUp = base.Service.GetHrSetUp();
            int months = setUp.Min_Leave_App_Months;
            model.leaveMonths = months;
            return EmployeeJoinDate.AddMonths(months).ToString(DATE_FORMAT);
        }

        public ActionResult LeaveBalance()
        {
            base.Init();
            ViewBag.IsSupervisor = base.UserIsSupervisor();
            // Prepopulate the model with the information of the currently logged in user.
            LeaveApplicationViewModel model = new LeaveApplicationViewModel();
            var userdata = base.Service.EmployeeData(User.Identity.EmployeeNo());
            if (userdata.Employee == null)
                return View("InvalidEmployeeDetail", InvalidEmployeeDetail());

            var UserIsSupervisor = base.Service.HasManagerialRole(userdata.Employee.Job_ID); //userdata.Employee.Employee_Type == EssPortal.EmployeeRef.Employee_Type.Manager ? true : false;
            var leaveRequestsForApprooval = base.Service.PendingLeaveToApprove(User.Identity.UserInformation().Email);

            model.EmployeeDataResponse = userdata;
            model.LeavePendingApproval = leaveRequestsForApprooval;
            model.UserIsSupervisor = UserIsSupervisor;
            model.Employees = base.EmployeeList();

            if (userdata.Success && userdata.Employee != null)
            {
                var employeeData = userdata.Employee;
                // Get the supervisor information and attach to the model
                //var approvalEntry = base.Service.GetApprovalUserSetUp(userdata.Employee.User_ID);
                var supervisor = base.Service.EmployeeData(employeeData.Supervisor_ID).Employee;

               
                model.EmployeeNo = employeeData.No;
                //model.Department = employeeData.Department_Name;
                model.EmployeeName = employeeData.First_Name + " " + employeeData.Middle_Name + " " + employeeData.Last_Name;

                model.TotalAnnualLeaveBalance = employeeData.Leave_Balance.ToString();
                model.TotalAnnualLeaveDays = employeeData.Total_Leave_Days.ToString(); // (employeeData.Leave_Balance + employeeData.Total_Leave_Taken).ToString();
                model.TotalAnnualLeaveTaken = employeeData.Total_Leave_Taken.ToString();
                model.AnnualLeaveDaysUtilized = employeeData.Total_Leave_Taken.ToString();

                return View(model);
            }
            else
            {
                Danger(userdata.ErrorMessage, true);
                return View(model);
            }
        }

        public ActionResult CreateLeaveRequest()
        {
            base.Init();
            ViewBag.IsSupervisor = base.UserIsSupervisor();
            // Prepopulate the model with the information of the currently logged in user.
            LeaveApplicationViewModel model = new LeaveApplicationViewModel();
            var userdata = base.Service.EmployeeData(User.Identity.EmployeeNo());
            if(userdata.Employee == null)
                return View("InvalidEmployeeDetail", InvalidEmployeeDetail());

            var UserIsSupervisor = base.Service.HasManagerialRole(userdata.Employee.Job_ID); //userdata.Employee.Employee_Type == EssPortal.EmployeeRef.Employee_Type.Manager ? true : false;
            var leaveRequestsForApprooval = base.Service.PendingLeaveToApprove(User.Identity.UserInformation().Email);

            model.EmployeeDataResponse = userdata;
            model.LeavePendingApproval = leaveRequestsForApprooval;
            model.UserIsSupervisor = UserIsSupervisor;
            model.StartDateOfApprovedLeave = new DateTime().ToString();
            model.EndDateOfApprovedLeave = new DateTime().ToString();
            model.Employees = base.EmployeeList();

            if (userdata.Success && userdata.Employee != null)
            {
                // Get the supervisor information and attach to the model
                //var approvalEntry = base.Service.GetApprovalUserSetUp(userdata.Employee.User_ID);
                var supervisorData = base.Service.EmployeeData(userdata.Employee.Supervisor_ID);
                var supervisor = supervisorData.Success && supervisorData.Employee != null ? supervisorData.Employee : new EmployeeRef.Employee();

                var employeeData = userdata.Employee;
                model.EmployeeNo = employeeData.No;
                model.EmployeeName = employeeData.First_Name + " " + employeeData.Middle_Name + " " + employeeData.Last_Name;
                model.JobTitle = employeeData.Job_Title;
                model.LeaveType = "Annual";
                model.Department = employeeData.Global_Dimension_1_Code;
                model.Branch = employeeData.Global_Dimension_2_Code;
                // Ensure the default date is not a weekend
                DateTime defaultDate = DateTime.Today.DayOfWeek == DayOfWeek.Saturday ? DateTime.Today.AddDays(2)
                    : DateTime.Today.DayOfWeek == DayOfWeek.Sunday ? DateTime.Today.AddDays(1)
                    : DateTime.Today;
                model.LeaveStartDate = defaultDate.ToString(DATE_FORMAT); // SET DEFAULT DATE VALUES
                model.LeaveEndDate = defaultDate.ToString(DATE_FORMAT); // SET DEFAULT DATE VALUES
                if (supervisor != null)
                {
                    model.SupervisorEmail = supervisor.Company_E_Mail;
                    model.SupervisorName = supervisor.First_Name + " " + supervisor.Middle_Name + " " + supervisor.Last_Name;
                }
                model.TotalAnnualLeaveBalance = employeeData.Leave_Balance.ToString();
                model.TotalAnnualLeaveDays = employeeData.Total_Leave_Days.ToString();
                model.TotalAnnualLeaveTaken = employeeData.Total_Leave_Taken.ToString();
                model.ApplicationDate = DateTime.Today.ToString(DATE_FORMAT);
                model.RejectionReason = ".";
                model.LeaveDaysApproved = "0";
                model.ValidLeaveDateFrom = employeeData.End_Of_Probation_Date.ToString(DATE_FORMAT);
                return View(model);
            }
            else
            {
                Danger(userdata.ErrorMessage, true);
                return View(model);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateLeaveRequest(LeaveApplicationViewModel model)
        {
            base.Init();
            ViewBag.IsSupervisor = base.UserIsSupervisor();
            var employeeNo = User.Identity.EmployeeNo();
            var userdata = base.Service.EmployeeData(employeeNo);
            if(userdata.Employee == null)
                return View("InvalidEmployeeDetail", InvalidEmployeeDetail());

            var UserIsSupervisor = base.Service.HasManagerialRole(userdata.Employee.Job_ID); //userdata.Employee.Employee_Type == EssPortal.EmployeeRef.Employee_Type.Manager ? true : false;
            model.UserIsSupervisor = UserIsSupervisor;
            // RETURN THE MODEL IF INVALID IS DISCOVERED.
            if (!ModelState.IsValid)
            {
                model.EmployeeDataResponse = base.Service.EmployeeData(employeeNo);
                model.LeavePendingApproval = base.Service.PendingLeaveToApprove(User.Identity.UserInformation().Email);
                model.Employees = base.EmployeeList();
                return View(model);
            }

            // create the empty leave application.
            string message = "";
            LeaveCreateResponse response = new LeaveCreateResponse();
            response = base.Service.CreateNewLeave(employeeNo, Service.StringToDate(model.LeaveStartDate), Service.StringToDate(model.LeaveEndDate));
            if (response.Success)
            {
                var leaveResponse = base.Service.GetLeaveApplication(response.NewLeaveNo, employeeNo, "");

                if (leaveResponse.Success && leaveResponse.Leave[0] != null)
                {
                    // Update the application with data from the incoming form. Editable fields only.
                    var leave = leaveResponse.Leave[0];
                    if (model.SubmitLeave)
                        leave.Status = LeaveRef.Status.Pending_Approval;
                    else
                        leave.Status = LeaveRef.Status.New;

EssPortal/Views/Leave/CreateLeaveRequest.cshtml
@model EssPortal.Models.LeaveApplicationViewModel

@{
    ViewBag.Title = "New Leave Request";
    Layout = "~/Views/Shared/_InnerPageLayout2.cshtml";
}


@using (Html.BeginForm("CreateLeaveRequest", "Leave", null, FormMethod.Post, new { id = "LeaveApplicationForm" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-lg-9">
            @Html.EditorFor(x => x)
            @Html.HiddenFor(m => m.StartDateOfApprovedLeave)
            @Html.HiddenFor(m => m.EndDateOfApprovedLeave)
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-lg-offset-3 col-md-9">
                        <input type="submit" value="Send for Approval" class="btn btn-default" id="SendForApproval" />
                        <input type="submit" value="Save" class="btn btn-default" id="SaveForEditing" />
                        <a href="@Url.Action("Index","Leave")" class="btn btn-default">Discard</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3">
            @Html.Partial("_LeaveBalance", Model.EmployeeDataResponse.Employee)
            @if (Model.UserIsSupervisor)
            {
                @Html.Partial("_PendingLeaveApprovePanel", Model.LeavePendingApproval.Leave)
            }
        </div>
    </div>
    <br />
}

@section Styles {
    <link href="@Url.Content("~/Content/css/select2.min.css")" rel="stylesheet" type="text/css" />
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    @{Html.RenderPartial("_LeaveScripts");}
    <script src="~/Scripts/select2.min.js" type="text/javascript"></script>

    <script type="text/javascript">
            var LeaveReliever = '@Model.RelieverCode';
    </script>
}

EssPortal/Views/Leave/Edit.cshtml
@model EssPortal.Models.LeaveApplicationViewModel

@{
    ViewBag.Title = "Edit Leave Request - " + Model.ApplicationNo;
    Layout = "~/Views/Shared/_InnerPageLayout2.cshtml";
}


@using (Html.BeginForm("Edit", "Leave", null, FormMethod.Post, new { id= "LeaveApplicationForm" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-lg-9">
            @Html.HiddenFor(m => m.StartDateOfApprovedLeave)
            @Html.HiddenFor(m => m.EndDateOfApprovedLeave)
            @Html.EditorFor(x => x)
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-9">
                        <input type="submit" value="Send for Approval" class="btn btn-default" id="SendForApproval" />
                        <input type="submit" value="Save" class="btn btn-default" id="SaveForEditing" />
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3">
            @Html.Partial("_LeaveBalance", Model.EmployeeDataResponse.Employee)
            @if (Model.UserIsSupervisor)
            {
                @Html.Partial("_PendingLeaveApprovePanel", Model.LeavePendingApproval.Leave)
            }
        </div>
    </div>
}

@section Styles {
    <link href="@Url.Content("~/Content/css/select2.min.css")" rel="stylesheet" type="text/css" />
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    @{Html.RenderPartial("_LeaveScripts");}
    
    <script src="~/Scripts/select2.min.js" type="text/javascript"></script>

    <script type="text/javascript">
        var LeaveReliever = '@Model.RelieverCode';
    </script>
}

EssPortal/Views/Leave/Index.cshtml
@model EssPortal.Models.LeaveIndexViewModel
@{
    ViewBag.Title = "Leave Summary";
    Layout = "~/Views/Shared/_InnerPageLayout2.cshtml";
    var employee = Model.EmployeeDataResponse.Employee;
}

<!-- /.row -->
<div class="row">
    <div class="col-lg-9">

        <div class="panel panel-default">
            <div class="panel-heading">
                Leave Request Summary
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover ">
                        <thead style="background-color:#f5f5f5">
                            <tr>
                                <th>Leave No</th>
                                <th>Application Date</th>
                                <th>Start Date</th>
                                <th>End Date</th>
                                <th>No. of Days Applied</th>
                                <th>No. of Days Approved</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.LeaveResponse.Leave)
                            {
                                <tr>
                                    <td>@item.Application_Code</td>
                                    <td>@item.Application_Date.ToString("dd/MM/yyyy")</td>
                                    <td>@item.Leave_Start_Date.ToString("dd/MM/yyyy")</td>
                                    <td>@item.Leave_End_Date.ToString("dd/MM/yyyy")</td>
                                    <td>@item.No_of_Leave_Days_Applied_for</td>
                                    <td>@item.No_of_Leave_Days_Approved</td>
                                    <td>
                                        @item.Status
                                        @if (item.Status == EssPortal.LeaveRef.Status.New)
                                        {
                                            /*ADD A EDIT LINK TO ENABLE EDITING THE APPLICATION*/
                                            <a href="@Url.Action("Edit", "Leave", new { ApplicationCode = item.Application_Code })" class="pull-right">Edit</a>
                                        }
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>


        <div class="row">
            <div class="col-lg-12">

            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <a href="@Url.Action("CreateLeaveRequest", "Leave")" class="btn btn-default">New Leave Application</a>
            </div>
        </div>
    </div>
    <!-- /.col-lg-8 -->
    <div class="col-lg-3">
        
        @Html.Partial("_LeaveBalance", employee)

        @if (Model.UserIsSupervisor)
        {
            @Html.Partial("_PendingLeaveApprovePanel", Model.LeavePendingApproval.Leave)
        }
    </div>
</div>

EssPortal/Views/Leave/LeaveBalance.cshtml
@model EssPortal.Models.LeaveApplicationViewModel

@{
    ViewBag.Title = "Leave Balance - " + Model.EmployeeNo;
    Layout = "~/Views/Shared/_InnerPageLayout2.cshtml";
}


@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-lg-9">

            <div class="form-horizontal">

                <div class="form-group">
                    @Html.LabelFor(model => model.EmployeeNo, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.EmployeeNo, new { htmlAttributes = new { @class = "form-control ", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.EmployeeNo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.EmployeeName, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.EmployeeName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.EmployeeName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TotalAnnualLeaveDays, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.TotalAnnualLeaveDays, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.TotalAnnualLeaveDays, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TotalAnnualLeaveTaken, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.TotalAnnualLeaveTaken, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.TotalAnnualLeaveTaken, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TotalAnnualLeaveBalance, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.TotalAnnualLeaveBalance, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.TotalAnnualLeaveBalance, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AnnualLeaveDaysUtilized, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.AnnualLeaveDaysUtilized, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.AnnualLeaveDaysUtilized, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-3">
            @Html.Partial("_LeaveBalance", Model.EmployeeDataResponse.Employee)
            @if (Model.UserIsSupervisor)
            {
                @Html.Partial("_PendingLeaveApprovePanel", Model.LeavePendingApproval.Leave)
            }
        </div>
    </div>
    <br />
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    @{Html.RenderPartial("_LeaveScripts");}
}

EssPortal/Views/Leave/SupervisorApprovedLeave.cshtml
@model EssPortal.Models.LeaveIndexViewModel
@{
    ViewBag.Title = "Approved Leave History";
    Layout = "~/Views/Shared/_InnerPageLayout2.cshtml";
    var employee = Model.EmployeeDataResponse.Employee;
}

<div class="row">
    <div class="col-lg-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                Leave applications approved by me
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover ">
                        <thead style="background-color:#f5f5f5">
                            <tr>
                                <th>Leave No</th>
                                <th>Employee No</th>
                                <th>Employee Name</th>
                                <th>Application Date</th>
                                <th>Start Date</th>
                                <th>End Date</th>
                                <th>No. of Days Applied</th>
                                <th>No. of Days Approved</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.LeaveResponse.Leave)
                            {
                                <tr>
                                    <td>@item.Application_Code</td>
                                    <td>@item.Employee_No</td>
                                    <td>@item.Names</td>
                                    <td>@item.Application_Date.ToString("dd/MM/yyyy")</td>
                                    <td>@item.Leave_Start_Date.ToString("dd/MM/yyyy")</td>
                                    <td>@item.Leave_End_Date.ToString("dd/MM/yyyy")</td>
                                    <td>@item.No_of_Leave_Days_Applied_for</td>
                                    <td>@item.No_of_Leave_Days_Approved</td>
                                    <td>@item.Status</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        @Html.Partial("_LeaveBalance", employee)

        @if (Model.UserIsSupervisor)
        {
            @Html.Partial("_PendingLeaveApprovePanel", Model.LeavePendingApproval.Leave)
        }
    </div>
</div>

EssPortal/Views/Leave/SupervisorEdit.cshtml
@model EssPortal.Models.LeaveApplicationViewModel

@{
    ViewBag.Title = "Leave Response Supervisor - " + Model.ApplicationNo;
    Layout = "~/Views/Shared/_InnerPageLayout2.cshtml";
}


@using (Html.BeginForm("SupervisorEdit", "Leave", null, FormMethod.Post, new { id= "LeaveApplicationForm" }))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-lg-9">
            @Html.EditorFor(x => x)

            @Html.HiddenFor(model => model.Approved, new { htmlAttributes = new { @class = "form-control" } })

            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-9">
                        <input type="submit" value="Approve" class="btn btn-default" id="ApproveLeave" />
                        <input type="submit" value="Reject" class="btn btn-default" id="RejectLeave" />
                        <a href="@Url.Action("Index","Manage")" class="btn btn-default"> Review Later </a>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-lg-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Employee @Model.EmployeeNo - Leave Balance
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="list-group">
                        <a href="#" class="list-group-item">
                            Total Leave days:
                            <span class="pull-right text-muted small">
                                <em>@Model.TotalAnnualLeaveDays days</em> <!--TODO UPDATE ALL FIELDS-->
                            </span>
                        </a>
                        <a href="#" class="list-group-item">
                            Leave days Taken:
                            <span class="pull-right text-muted small">
                                <em>@Model.TotalAnnualLeaveTaken days</em>
                            </span>
                        </a>
                        <a href="#" class="list-group-item">
                            Leave Balance:
                            <span class="pull-right text-muted small">
                                <em>@Model.TotalAnnualLeaveBalance days</em>
                            </span>
                        </a>
                    </div>
                </div>
            </div>

            @Html.Partial("_PendingLeaveApprovePanel", Model.LeavePendingApproval.Leave)
        </div>
    </div>
}

@section Styles {
    <link href="@Url.Content("~/Content/css/select2.min.css")" rel="stylesheet" type="text/css" />
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    @{Html.RenderPartial("_LeaveScripts");}
    <script src="~/Scripts/select2.min.js" type="text/javascript"></script>

    <script type="text/javascript">
            var LeaveReliever = '@Model.RelieverCode';
    </script>
}